# Deep copy

In [2154]:
a = [[1, 2, 3, 4], [3, 4, 5, 6]]
b = a[:]

In [2155]:
a, b

([[1, 2, 3, 4], [3, 4, 5, 6]], [[1, 2, 3, 4], [3, 4, 5, 6]])

In [2156]:
a[0][0] = 5
a, b

([[5, 2, 3, 4], [3, 4, 5, 6]], [[5, 2, 3, 4], [3, 4, 5, 6]])

In [2157]:
from copy import deepcopy

In [2158]:
a = [[1, 2, 3, 4], [3, 4, 5, 6]]
b = deepcopy(a)

In [2159]:
a, b

([[1, 2, 3, 4], [3, 4, 5, 6]], [[1, 2, 3, 4], [3, 4, 5, 6]])

In [2160]:
a[0][0] = 1000
a, b

([[1000, 2, 3, 4], [3, 4, 5, 6]], [[1, 2, 3, 4], [3, 4, 5, 6]])

# Array creation

In [2161]:
import numpy as np

In [2162]:
test_array = np.array([1, 4, 5, '8'], float) # str and int
# test_array = np.array([1, 4, 5, '8'], np.float32) # Memory reduction
test_array

array([1., 4., 5., 8.])

In [2163]:
type(test_array[3])

numpy.float64

In [2164]:
test_array.dtype

dtype('float64')

# Shape

In [2165]:
test_array.shape

(4,)

In [2166]:
tmp = test_array
test_array = np.array([[1, 4, 5, '8']], float)
test_array.shape

(1, 4)

In [2167]:
matrix = [
    [1, 2, 5, 8],
    [1, 2, 5, 8],
    [1, 2, 5, 8],
]
np.array(matrix, int).shape

(3, 4)

In [2168]:
# Third order tensor
tensor = [
    [
        [1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8],
    ],
    [
        [1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8],
    ],
    [
        [1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8],
    ],
    [
        [1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8],
    ],
]
np_tensor = np.array(tensor, int)
np_tensor.shape, np_tensor # 차원이 추가될 때마다 하나씩 밀리는 형태

((4, 3, 4),
 array([[[1, 2, 5, 8],
         [1, 2, 5, 8],
         [1, 2, 5, 8]],
 
        [[1, 2, 5, 8],
         [1, 2, 5, 8],
         [1, 2, 5, 8]],
 
        [[1, 2, 5, 8],
         [1, 2, 5, 8],
         [1, 2, 5, 8]],
 
        [[1, 2, 5, 8],
         [1, 2, 5, 8],
         [1, 2, 5, 8]]]))

In [2169]:
np_tensor.ndim

3

In [2170]:
np_tensor.size # Size of data

48

# Memory size

In [2171]:
np_tensor.size * 8, np_tensor.nbytes # float64[8] * np_tensor.size

(384, 384)

In [2172]:
i_ndarray = np.array(['1', '2', '3', '4', '5', '5'], np.int8)
i_ndarray.nbytes

6

# Shaping

In [2173]:
np_tensor.shape

(4, 3, 4)

In [2174]:
np_tensor.reshape(np_tensor.size).shape

(48,)

In [2175]:
np_tensor.reshape(4, 6, -1).shape # -1

(4, 6, 2)

In [2176]:
n_1d_array = np.array([1, 2, 3, 4, 4, 4, 5, 6], float)
n_1d_array.shape

(8,)

In [2177]:
n_2d_array = n_1d_array.reshape(-1, 1) # (8, 1)
# n_2d_array = n_1d_array.reshape(1, -1) # (1, 8)

n_2d_array, n_2d_array.shape

(array([[1.],
        [2.],
        [3.],
        [4.],
        [4.],
        [4.],
        [5.],
        [6.]]),
 (8, 1))

In [2178]:
# Flatter

np_tensor.shape
np_tensor.shape, np_tensor.flatten().shape

((4, 3, 4), (48,))

# Indexing and Slicing

In [2179]:
l = []
items = [1, 2, 5, 8]

for i in range(4):
    l.append(items)
    
l
matrix = np.array(l, int)
matrix, matrix.shape

(array([[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]]),
 (4, 4))

In [2180]:
sliced = matrix[:2, :] # 0, 1 // All == 1, 2 * 4  (2, 4)
sliced, sliced.shape

(array([[1, 2, 5, 8],
        [1, 2, 5, 8]]),
 (2, 4))

In [2181]:
sliced01 = matrix[:, 1:3] # All, // 1, 2 == All // 2, 5 (4, 2)
sliced02 = matrix[1, :2] # Sec_row // 1, 2 (1, 2)( == (2, ))

sliced01, sliced01.shape, sliced02, sliced02.shape

(array([[2, 5],
        [2, 5],
        [2, 5],
        [2, 5]]),
 (4, 2),
 array([1, 2]),
 (2,))

# Creation functions

## arange

In [2182]:
np_ar = np.arange(30)
np_ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [2183]:
np_ar = np.arange(0, 5, 0.5)
np_ar

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [2184]:
l_ar = np_ar.tolist()
l_ar, type(l_ar)

([0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5], list)

In [2185]:
np_ar.reshape(5, -1), np_ar.reshape(5, -1).shape

(array([[0. , 0.5],
        [1. , 1.5],
        [2. , 2.5],
        [3. , 3.5],
        [4. , 4.5]]),
 (5, 2))

## ones, zeroes and empty

In [2186]:
np.zeros((10,), np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [2187]:
np.zeros((2, 5)), np.zeros((2, 5)).dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 dtype('float64'))

In [2188]:
np.ones((3, 1, 5), np.float32)

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]], dtype=float32)

In [2189]:
# Do not memory-initialization

np.empty((10, 1, 2), np.int64)

array([[[                0,      489626273787]],

       [[     261993005088,      472446402592]],

       [[     408021893232,      489626271841]],

       [[     498216206382,      463856468079]],

       [[     493921239145,      171798691956]],

       [[      42949673001,      408021893228]],

       [[     489626271841,      137438953516]],

       [[     519691042932,      433791697008]],

       [[     463856468008,      416611827807]],

       [[     176093659250, 35243978475253816]]])

## (something)_like

In [2190]:
test_matrix = np.arange(30).reshape(5, -5)
test_matrix, test_matrix.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 (5, 6))

In [2191]:
np.ones_like(test_matrix), np.ones_like(test_matrix).shape

(array([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]),
 (5, 6))

## identity

In [2192]:
np.identity(3, np.int8)
# np.identity(3, np.float32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [2193]:
np.identity(5), np.identity(5).dtype

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 dtype('float64'))

## eye

In [2194]:
np.eye(N=3, M=5, k=2, dtype=np.int8) # k for shifting [Start index]

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [2195]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## diag: 대각 행렬의 값 추출

In [2196]:
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix)

array([0, 4, 8])

In [2197]:
np.diag(matrix, k=1)

array([1, 5])

## Random sampling

In [2198]:
np.random.uniform(0, 1, 10).reshape(2, 5) # 균등분포

array([[0.18105876, 0.60266048, 0.77109028, 0.79035623, 0.55332331],
       [0.10199939, 0.92647416, 0.25675526, 0.94979506, 0.72616819]])

In [2199]:
np.random.normal(0, 1, 10).reshape(2, 5) # 정규분포

array([[ 0.36936472,  1.54235993, -0.46094781, -0.9424855 ,  0.20621614],
       [-0.74966938, -0.28733991, -0.68989759,  0.40796938,  1.30404128]])

## sum

In [2200]:
test_array = np.arange(1, 11)
sum = test_array.sum(dtype=np.float32)
sum, sum.dtype

(55.0, dtype('float32'))

## axis

In [2201]:
test_array = np.arange(12).reshape(3, 4)
test_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2202]:
test_array.sum(axis=0), test_array.sum(axis=1), test_array.sum(axis=0).shape, test_array.sum(axis=0).shape

(array([12, 15, 18, 21]), array([ 6, 22, 38]), (4,), (4,))

In [2203]:
test_array = np.array([test_array, test_array, test_array], np.int8)
test_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]], dtype=int8)

In [2204]:
test_array.sum(axis=0), test_array.sum(axis=1), test_array.sum(axis=2)

(array([[ 0,  3,  6,  9],
        [12, 15, 18, 21],
        [24, 27, 30, 33]]),
 array([[12, 15, 18, 21],
        [12, 15, 18, 21],
        [12, 15, 18, 21]]),
 array([[ 6, 22, 38],
        [ 6, 22, 38],
        [ 6, 22, 38]]))

## Concatenation

In [2205]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])

v = np.vstack((x, y))
v, v.shape

(array([[1, 2, 3],
        [2, 3, 4]]),
 (2, 3))

In [2206]:
x = x.reshape(3, -1)
y = x.reshape(3, -1)

h = np.hstack((x, y))
h

array([[1, 1],
       [2, 2],
       [3, 3]])

### np.concatenate()

In [2207]:
a = np.array([
    [1, 2, 3]
])
b = np.array([
    [2, 3, 4]
])

np.concatenate((a, b)), np.concatenate((a, b)).shape

(array([[1, 2, 3],
        [2, 3, 4]]),
 (2, 3))

In [2208]:
a = np.array([
    [1, 2],
    [3, 4],
])
b = np.array([
    [5, 6]
])

# np.concatenate((a, b), axis=1) # Value error
b.T, b.T.shape, np.concatenate((a, b.T), axis=1)

(array([[5],
        [6]]),
 (2, 1),
 array([[1, 2, 5],
        [3, 4, 6]]))

# Array operations

In [2209]:
test_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
], float)

test_a + test_a, test_a - test_a, test_a * test_a

(array([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[ 1.,  4.,  9.],
        [16., 25., 36.]]))

## Dot product

In [2210]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

test_a.dot(test_b), test_a.dot(test_b).shape

(array([[ 58,  64],
        [139, 154]]),
 (2, 2))

In [2211]:
test_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
])
scalar = 3

test_matrix + scalar

array([[4, 5, 6],
       [7, 8, 9]])

In [2212]:
scalar = 0.2
test_matrix // scalar

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

# Comparison

## all, any

In [2213]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2214]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [2215]:
np.any(a > 5), np.any(a < 0)

(True, False)

In [2216]:
np.all(a > 5), np.all(a < 10)

(False, True)

## logical_and/or/not

In [2217]:
a = np.array([1, 3, 0], float)
a

array([1., 3., 0.])

In [2218]:
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [2219]:
b = np.array([True, False, True])
b

array([ True, False,  True])

In [2220]:
np.logical_not(b)

array([False,  True, False])

In [2221]:
c = np.array([False, True, True], bool)
np.logical_or(b, c), np.logical_and(b, c)

(array([ True,  True,  True]), array([False, False,  True]))

## where

In [2222]:
# np.where(a > 0)
np.where(a > 0, 33, 22) # Return True=32, False=22

array([33, 33, 22])

In [2223]:
a = np.arange(10)
np.where(a > 5)

(array([6, 7, 8, 9]),)

In [2224]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [2225]:
np.isfinite(a)

array([ True, False, False])

## argmin, argmax

In [2226]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a)

/opt/homebrew/Caskroom/miniforge/base/envs/main/lib/python3.9/site-packages/IPython/core/displayhook.py:275: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'


(5, 0)

In [2227]:
a = np.array([
    [1, 2, 4, 7],
    [9, 88, 6, 45],
    [9, 76, 3, 4],
])
np.argmin(a), np.argmax(a, axis=1)

(0, array([3, 1, 1]))

# Boolean and Fancy index

In [2228]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [2229]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [2230]:
cond = test_array < 3
test_array[cond]

array([1., 0., 2.])

## To binary

In [2231]:
test_array = test_array.reshape(2, 2, -1)
test_array

array([[[1., 4.],
        [0., 2.]],

       [[3., 8.],
        [9., 7.]]])

In [2232]:
cond = test_array > 4
# cond.astype(np.bool8).nbytes, cond.size
cond.astype(np.bool8)

array([[[False, False],
        [False, False]],

       [[False,  True],
        [ True,  True]]])

## Fancy index

In [2233]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # Warning: Should integer
a[b]

array([2., 2., 4., 8., 6., 4.])

In [2234]:
a.take(b) # Recommended

array([2., 2., 4., 8., 6., 4.])

In [2235]:
a = np.array([
    [1, 4],
    [9, 16],
], float)
b = np.array([
    0, 0, 1, 1, 0
], int)
c = np.array([
    0, 1, 1, 1, 1
], int)

a[b, c] # b: row idx, c: col idx

array([ 1.,  4., 16., 16.,  4.])

# Save and Load

In [2236]:
np.save('out/np_test', arr=(a[b, c] ** 2))

## Load

In [2237]:
np_test = np.load(file='out/np_test.npy')
np_test, np_test.shape

(array([  1.,  16., 256., 256.,  16.]), (5,))