In [1]:
import torch
import numpy as np

/opt/homebrew/Caskroom/miniforge/base/envs/main/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a = torch.FloatTensor([
    [1, 2],
    [3, 4],
])
b = torch.FloatTensor([
    [2, 2],
    [3, 3],
])

f = lambda x: print(x, x.dtype)

In [3]:
f(a)

tensor([[1., 2.],
        [3., 4.]]) torch.float32


In [4]:
f(b)

tensor([[2., 2.],
        [3., 3.]]) torch.float32


In [5]:
# Element-wise opreation

f(a + b)

tensor([[3., 4.],
        [6., 7.]]) torch.float32


In [6]:
# Output torch.bool

f(a == b)

tensor([[False,  True],
        [ True, False]]) torch.bool


In [7]:
# Element-wise operation too

f(a ** b)

tensor([[ 1.,  4.],
        [27., 64.]]) torch.float32


# Inplace Operations

In [8]:
print(a, a.mul(b))

tensor([[1., 2.],
        [3., 4.]]) tensor([[ 2.,  4.],
        [ 9., 12.]])


In [9]:
# Inplace

print(a, a.mul_(b))

tensor([[ 2.,  4.],
        [ 9., 12.]]) tensor([[ 2.,  4.],
        [ 9., 12.]])


# Demention Reducing Operations

In [10]:
x = torch.FloatTensor([
    [1, 2],
    [3, 4]
])
x

tensor([[1., 2.],
        [3., 4.]])

In [11]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [12]:
print(x.sum(dim=0)) # dim=N, Dimension 'N' to hided
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


# Broadcasting Operations

In [13]:
x = torch.FloatTensor(
    [
        [1, 2],
        [3, 4],
    ]
)
x.shape

torch.Size([2, 2])

In [14]:
y = 1

In [15]:
z = x + y

print(z, z.size())

tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


## Tensor + Vector

In [16]:
x = torch.FloatTensor([
    [1, 2],
    [4, 8]
])
x, x.size()

(tensor([[1., 2.],
         [4., 8.]]),
 torch.Size([2, 2]))

In [17]:
y = torch.FloatTensor([
    3,
    5
])
y, y.size()

(tensor([3., 5.]), torch.Size([2]))

In [18]:
z = x + y
z, z.size()

(tensor([[ 4.,  7.],
         [ 7., 13.]]),
 torch.Size([2, 2]))

In [19]:
x = torch.FloatTensor([
    [
        [1, 2]
    ]
])
f = lambda x: print(x, x.size())
f(x)

tensor([[[1., 2.]]]) torch.Size([1, 1, 2])


In [20]:
y = torch.FloatTensor([
    3, 5
])
f(y)

tensor([3., 5.]) torch.Size([2])


In [21]:
z = x + y

f(x)
f(y)
f(z)

tensor([[[1., 2.]]]) torch.Size([1, 1, 2])
tensor([3., 5.]) torch.Size([2])
tensor([[[4., 7.]]]) torch.Size([1, 1, 2])


## Tensor + Tensor

In [26]:
x = torch.FloatTensor([
    [1, 2]
])
y = torch.FloatTensor([
    [3], 
    [5]
])

f(x)
f(y)

tensor([[1., 2.]]) torch.Size([1, 2])
tensor([[3.],
        [5.]]) torch.Size([2, 1])


In [27]:
z = x + y

f(z)

tensor([[4., 5.],
        [6., 7.]]) torch.Size([2, 2])


## Failure Cases

In [30]:
# [1, 2, 2]
# [3, 3]

x = torch.FloatTensor([
    [
        [11, 22],
        [33, 44]
    ]
])
y = torch.FloatTensor([
    [11, 22, 33],
    [11, 22, 33],
    [11, 22, 33],
])

f(x)
f(y)

tensor([[[11., 22.],
         [33., 44.]]]) torch.Size([1, 2, 2])
tensor([[11., 22., 33.],
        [11., 22., 33.],
        [11., 22., 33.]]) torch.Size([3, 3])


In [31]:
z = x + y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2