In [1]:
import torch

/opt/homebrew/Caskroom/miniforge/base/envs/main/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Reshaping

In [2]:
x = torch.FloatTensor([
    [
        [1, 2],
        [3, 4],
    ],
    [
        [1, 2],
        [3, 4],
    ],
    [
        [1, 2],
        [11, 12],
    ]
])

f = lambda x: print(x, x.size())

f(x)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 1.,  2.],
         [ 3.,  4.]],

        [[ 1.,  2.],
         [11., 12.]]]) torch.Size([3, 2, 2])


In [3]:
f(x.reshape(12))

tensor([ 1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.,  1.,  2., 11., 12.]) torch.Size([12])


In [6]:
f(x.reshape(3, 4)) # (3, 4)
f(x.reshape(3, -1)) # (3, 4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 1.,  2., 11., 12.]]) torch.Size([3, 4])
tensor([[ 1.,  2.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 1.,  2., 11., 12.]]) torch.Size([3, 4])


In [7]:
f(x.reshape(3, 1, 4))
f(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 1.,  2.,  3.,  4.]],

        [[ 1.,  2., 11., 12.]]]) torch.Size([3, 1, 4])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 1.,  2.,  3.,  4.]],

        [[ 1.,  2., 11., 12.]]]) torch.Size([3, 1, 4])


In [8]:
f(x.reshape(3, 2, 2, 1))
f(x.reshape(3, 1, 1, 4))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 1.],
          [ 2.]],

         [[11.],
          [12.]]]]) torch.Size([3, 2, 2, 1])
tensor([[[[ 1.,  2.,  3.,  4.]]],


        [[[ 1.,  2.,  3.,  4.]]],


        [[[ 1.,  2., 11., 12.]]]]) torch.Size([3, 1, 1, 4])


In [9]:
# view() + contiguos(?) == reshape()

f(x.view(3, 2, 2, 1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 1.],
          [ 2.]],

         [[11.],
          [12.]]]]) torch.Size([3, 2, 2, 1])


## Squeezing

In [11]:
x = torch.FloatTensor([
    [
        [1, 2],
        [1, 2],
    ]
])
f(x)

tensor([[[1., 2.],
         [1., 2.]]]) torch.Size([1, 2, 2])


In [12]:
f(x.squeeze())

tensor([[1., 2.],
        [1., 2.]]) torch.Size([2, 2])


In [14]:
f(x.squeeze(dim=0))
f(x.squeeze(1))

tensor([[1., 2.],
        [1., 2.]]) torch.Size([2, 2])
tensor([[[1., 2.],
         [1., 2.]]]) torch.Size([1, 2, 2])


## Unsqueezing

In [23]:
x = torch.FloatTensor([
    [1, 2],
    [1, 2],
])
f(x)

tensor([[1., 2.],
        [1., 2.]]) torch.Size([2, 2])


In [25]:
f(x.unsqueeze(dim=2))
f(x.unsqueeze(-1))
f(x.reshape(2, 2, -1))

tensor([[[1.],
         [2.]],

        [[1.],
         [2.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[1.],
         [2.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[1.],
         [2.]]]) torch.Size([2, 2, 1])
