In [1]:
import torch

/opt/homebrew/Caskroom/miniforge/base/envs/main/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import numpy as np

In [7]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [8]:
ft = torch.FloatTensor([
    [1, 2],
    [3, 4]
])
print(ft, type(ft))

tensor([[1., 2.],
        [3., 4.]]) <class 'torch.Tensor'>


In [9]:
lt = torch.LongTensor([
    [1, 2],
    [3, 4],
])
print(lt, type(lt))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [11]:
bt = torch.ByteTensor([
    [1, 0],
    [0, 1],
])
print(bt, type(bt))

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8) <class 'torch.Tensor'>


In [30]:
x = torch.FloatTensor(3, 2) # Garbage value
print(x, type(x))

tensor([[ 1.3151e-28, -1.5846e+29],
        [ 1.6898e-38,  1.4013e-45],
        [ 0.0000e+00, -0.0000e+00]]) <class 'torch.Tensor'>


In [6]:
x = np.array([
    [1, 2],
    [3, 4]
])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [31]:
# To ndarray

x = x.numpy()
print(x, type(x))

[[ 1.3151128e-28 -1.5845633e+29]
 [ 1.6897740e-38  1.4012985e-45]
 [ 0.0000000e+00 -0.0000000e+00]] <class 'numpy.ndarray'>


In [45]:
# To Long-tensor

ft = ft.long()
l = lambda x: print(x, x.dtype)

l(ft)

tensor([[1, 2],
        [3, 4]]) torch.int64


In [50]:
x = torch.FloatTensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ],
    [
        [9 ,10],
        [11 ,12]
    ],
])

In [48]:
print(x.shape)
print(x.size())

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [52]:
print(x.dim(), len(x.size()))

3 3


In [54]:
print(x.size(1))
print(x.shape[1])

2
2
