In [1]:
import torch
import numpy as np

/opt/homebrew/Caskroom/miniforge/base/envs/main/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
a = torch.FloatTensor([
    [1, 2],
    [3, 4],
])
b = torch.FloatTensor([
    [2, 2],
    [3, 3],
])

f = lambda x: print(x, x.dtype)

In [6]:
f(a)

tensor([[1., 2.],
        [3., 4.]]) torch.float32


In [7]:
f(b)

tensor([[2., 2.],
        [3., 3.]]) torch.float32


In [9]:
# Element-wise opreation

f(a + b)

tensor([[3., 4.],
        [6., 7.]]) torch.float32


In [11]:
# Output torch.bool

f(a == b)

tensor([[False,  True],
        [ True, False]]) torch.bool


In [12]:
# Element-wise operation too

f(a ** b)

tensor([[ 1.,  4.],
        [27., 64.]]) torch.float32


# Inplace Operations

In [14]:
print(a, a.mul(b))

tensor([[1., 2.],
        [3., 4.]]) tensor([[ 2.,  4.],
        [ 9., 12.]])


In [16]:
# Inplace

print(a, a.mul_(b))

tensor([[ 4.,  8.],
        [27., 36.]]) tensor([[ 4.,  8.],
        [27., 36.]])


# Demention Reducing Operations

In [19]:
x = torch.FloatTensor([
    [1, 2],
    [3, 4]
])
x

tensor([[1., 2.],
        [3., 4.]])

In [21]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [26]:
print(x.sum(dim=0))
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])
