# Useful functions

In [1]:
import torch

/opt/homebrew/Caskroom/miniforge/base/envs/main/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Expand

In [3]:
x = torch.FloatTensor([
    [
        [1, 2],
    ],
    [
        [3, 4],
    ],
])

f = lambda x: print(x, x.size())

f(x)

tensor([[[1., 2.]],

        [[3., 4.]]]) torch.Size([2, 1, 2])


In [4]:
y = x.expand(*[2, 3, 2])

f(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


### Hard way

In [5]:
y = torch.cat([x, x, x], 1)

f(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


## Random premutation

In [6]:
x = torch.randperm(10)

f(x)

tensor([4, 5, 6, 1, 9, 3, 7, 0, 8, 2]) torch.Size([10])


## Argument max

In [7]:
x = torch.randperm(3 ** 3).reshape(3, 3, -1)

f(x)

tensor([[[12, 22,  9],
         [ 6,  3, 14],
         [24, 19,  0]],

        [[10, 15,  7],
         [17,  1, 11],
         [20, 18, 16]],

        [[25, 26, 21],
         [13,  2,  4],
         [ 5, 23,  8]]]) torch.Size([3, 3, 3])


In [8]:
y = x.argmax(-1)

f(y)

tensor([[1, 2, 0],
        [1, 0, 0],
        [1, 0, 1]]) torch.Size([3, 3])


## Top-k values and indices

In [9]:
values, indices = torch.topk(x, 1, -1)

f(values)
f(indices)

tensor([[[22],
         [14],
         [24]],

        [[15],
         [17],
         [20]],

        [[26],
         [13],
         [23]]]) torch.Size([3, 3, 1])
tensor([[[1],
         [2],
         [0]],

        [[1],
         [0],
         [0]],

        [[1],
         [0],
         [1]]]) torch.Size([3, 3, 1])
