In [26]:
import torch
import torch.nn.functional as F

In [27]:
target = torch.FloatTensor([
    [.1, .2, .3],
    [.4, .5, .6],
    [.7, .8, .9],
])

f = lambda x: print(x, x.size())

f(target)

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]]) torch.Size([3, 3])


In [28]:
x = torch.rand_like(target).requires_grad_(True)
f(x)

tensor([[0.8952, 0.0794, 0.0625],
        [0.3844, 0.8278, 0.4688],
        [0.5667, 0.7281, 0.9404]], requires_grad=True) torch.Size([3, 3])


In [29]:
loss = F.mse_loss(x, target)
loss

tensor(0.0948, grad_fn=<MseLossBackward0>)

In [30]:
threshold = 1e-5
lr = 1
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1

    loss.backward()

    x = x - (lr * x.grad)

    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(x, target)

    print(f'{iter_cnt}-th Loss: %.4e' % loss)
    print(x)

1-th Loss: 5.7321e-02
tensor([[0.7185, 0.1062, 0.1153],
        [0.3879, 0.7549, 0.4980],
        [0.5963, 0.7441, 0.9315]], requires_grad=True)
2-th Loss: 3.4676e-02
tensor([[0.5811, 0.1270, 0.1563],
        [0.3906, 0.6983, 0.5206],
        [0.6194, 0.7565, 0.9245]], requires_grad=True)
3-th Loss: 2.0977e-02
tensor([[0.4742, 0.1433, 0.1883],
        [0.3927, 0.6542, 0.5383],
        [0.6373, 0.7662, 0.9190]], requires_grad=True)
4-th Loss: 1.2690e-02
tensor([[0.3910, 0.1559, 0.2131],
        [0.3943, 0.6200, 0.5520],
        [0.6512, 0.7737, 0.9148]], requires_grad=True)
5-th Loss: 7.6764e-03
tensor([[0.3263, 0.1657, 0.2324],
        [0.3956, 0.5933, 0.5627],
        [0.6621, 0.7795, 0.9115]], requires_grad=True)
6-th Loss: 4.6438e-03
tensor([[0.2760, 0.1733, 0.2474],
        [0.3965, 0.5726, 0.5710],
        [0.6705, 0.7841, 0.9090]], requires_grad=True)
7-th Loss: 2.8092e-03
tensor([[0.2369, 0.1792, 0.2591],
        [0.3973, 0.5564, 0.5774],
        [0.6770, 0.7876, 0.9070]], requi