# PyTorch AutoGrad

In [25]:
import torch

In [26]:
x = torch.FloatTensor([
    [1, 2],
    [3, 4],
]).requires_grad_(True)

f = lambda x: print(x, x.size())

f(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True) torch.Size([2, 2])


In [27]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

f(x1)
f(x2)
f(x3)
f(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>) torch.Size([2, 2])
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>) torch.Size([2, 2])
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>) torch.Size([2, 2])
tensor(14., grad_fn=<SumBackward0>) torch.Size([])


In [28]:
y.backward() # y.type == scalar

In [29]:
f(x.grad)

tensor([[2., 4.],
        [6., 8.]]) torch.Size([2, 2])


In [30]:
f(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True) torch.Size([2, 2])


In [31]:
f(x3)

tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>) torch.Size([2, 2])


In [32]:
x3.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [34]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)