In [1]:
import torch

/opt/homebrew/Caskroom/miniforge/base/envs/main/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Raw linear layer

In [2]:
W = torch.FloatTensor([
    [1, 2],
    [3, 4],
    [5, 6],
])
b = torch.FloatTensor([
    2, 2
])

f = lambda x: print(x, x.size())

f(W)
f(b)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) torch.Size([3, 2])
tensor([2., 2.]) torch.Size([2])


In [3]:
def linear(x, W, b):
    y = torch.matmul(x, W) + b
    return y

In [4]:
x = torch.FloatTensor([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3],
    [4, 4, 4],
])
f(x)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]]) torch.Size([4, 3])


In [5]:
y = linear(x, W, b)
f(y)

tensor([[11., 14.],
        [20., 26.],
        [29., 38.],
        [38., 50.]]) torch.Size([4, 2])
