In [5]:
import torch

In [10]:
def mse(x_hat, x):
    y = ((x - x_hat) ** 2).mean()
    return y

In [8]:
f = lambda x: print(x, x.size())

x = torch.FloatTensor([
    [1, 1],
    [2, 2],
])
x_hat = torch.FloatTensor([
    [0, 0],
    [0, 0],
])

f(x)
f(x_hat)

tensor([[1., 1.],
        [2., 2.]]) torch.Size([2, 2])
tensor([[0., 0.],
        [0., 0.]]) torch.Size([2, 2])


In [11]:
mse(x_hat, x)

tensor(2.5000)

# Predefined in Torch

In [12]:
import torch.nn.functional as F

In [13]:
F.mse_loss(x_hat, x)

tensor(2.5000)

In [18]:
F.mse_loss(x_hat, x, reduction='sum')

tensor(10.)

In [19]:
F.mse_loss(x_hat, x, reduction='none')

tensor([[1., 1.],
        [4., 4.]])

In [20]:
import torch.nn as nn

In [21]:
mse_loss = nn.MSELoss()

In [22]:
mse_loss(x_hat, x)

tensor(2.5000)