# TODO
* For Machine Learning, Study again *numpy*, *pandas*
* Practice Vector operation using *numpy*

In [1]:
import numpy as np
import pandas as pd

## Generate Vector

In [2]:
v1 = np.array([1, 2, 3])
v1

array([1, 2, 3])

In [3]:
v2 = np.array([0, 0, 0])
v2

array([0, 0, 0])

## Operations

In [4]:
v1 + v2

array([1, 2, 3])

In [5]:
v2 - v1

array([-1, -2, -3])

In [6]:
v1 * v2 # Element-wise Multiplication

array([0, 0, 0])

In [7]:
v2 / v1 # Element-wise Division

array([0., 0., 0.])

In [8]:
v1 * 2

array([2, 4, 6])

In [9]:
1 / v1

array([1.        , 0.5       , 0.33333333])

## Example

In [23]:
data = pd.read_csv('../data/Kaggle-Prudencial-Assess/train.csv')
data

Id  Product_Info_1 Product_Info_2  Product_Info_3  Product_Info_4  \
0          2               1             D3              10        0.076923   
1          5               1             A1              26        0.076923   
2          6               1             E1              26        0.076923   
3          7               1             D4              10        0.487179   
4          8               1             D2              26        0.230769   
...      ...             ...            ...             ...             ...   
59376  79142               1             D1              10        0.230769   
59377  79143               1             D3              26        0.230769   
59378  79144               1             E1              26        0.076923   
59379  79145               1             D2              10        0.230769   
59380  79146               1             A8              26        0.076923   

       Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  \
0                   2               1               1  0.641791  0.581818   
1                   2               3               1  0.059701  0.600000   
2                   2               3               1  0.029851  0.745455   
3                   2               3               1  0.164179  0.672727   
4                   2               3               1  0.417910  0.654545   
...               ...             ...             ...       ...       ...   
59376               2               3               1  0.074627  0.709091   
59377               2               3               1  0.432836  0.800000   
59378               2               3               1  0.104478  0.745455   
59379               2               3               1  0.507463  0.690909   
59380               2               3               1  0.447761  0.781818   

       ...  Medical_Keyword_40  Medical_Keyword_41  Medical_Keyword_42  \
0      ...                   0                   0                   0   
1      ...                   0                   0                   0   
2      ...                   0                   0                   0   
3      ...                   0                   0                   0   
4      ...                   0                   0                   0   
...    ...                 ...                 ...                 ...   
59376  ...                   0                   0                   0   
59377  ...                   0                   0                   0   
59378  ...                   0                   0                   0   
59379  ...                   1                   0                   0   
59380  ...                   0                   0                   0   

       Medical_Keyword_43  Medical_Keyword_44  Medical_Keyword_45  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
59376                   0                   0                   0   
59377                   0                   0                   0   
59378                   0                   0                   0   
59379                   0                   0                   0   
59380                   0                   0                   0   

       Medical_Keyword_46  Medical_Keyword_47  Medical_Keyword_48  Response  
0                       0                   0                   0         8  
1                       0                   0                   0         4  
2                       0                   0                   0         8  
3                       0                   0                   0         8  
4                       0   

### Get mini-data

In [25]:
data_mini = data.iloc[:100, :15]
data_mini

Id  Product_Info_1 Product_Info_2  Product_Info_3  Product_Info_4  \
0     2               1             D3              10        0.076923   
1     5               1             A1              26        0.076923   
2     6               1             E1              26        0.076923   
3     7               1             D4              10        0.487179   
4     8               1             D2              26        0.230769   
..  ...             ...            ...             ...             ...   
95  134               1             D3              26        0.358974   
96  135               1             D2              26        1.000000   
97  136               1             D2              26        0.487179   
98  137               1             D4              26        0.743590   
99  138               1             D4              10        0.076923   

    Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  \
0                2               1               1  0.641791  0.581818   
1                2               3               1  0.059701  0.600000   
2                2               3               1  0.029851  0.745455   
3                2               3               1  0.164179  0.672727   
4                2               3               1  0.417910  0.654545   
..             ...             ...             ...       ...       ...   
95               2               1               3  0.582090  0.709091   
96               2               3               1  0.432836  0.690909   
97               2               3               1  0.388060  0.872727   
98               2               1               1  0.283582  0.800000   
99               2               3               1  0.179104  0.672727   

          Wt       BMI  Employment_Info_1  Employment_Info_2  \
0   0.148536  0.323008              0.028                 12   
1   0.131799  0.272288              0.000                  1   
2   0.288703  0.428780              0.030                  9   
3   0.205021  0.352438              0.042                  9   
4   0.234310  0.424046              0.027                  9   
..       ...       ...                ...                ...   
95  0.372385  0.608927              0.072                  9   
96  0.236402  0.392133              0.120                 12   
97  0.560669  0.687138              0.065                  9   
98  0.267782  0.348473              0.130                  9   
99  0.236402  0.409648              0.095                  1   

    Employment_Info_3  
0                   1  
1                   3  
2                   1  
3                   1  
4                   1  
..                ...  
95                  1  
96                  1  
97                  1  
98                  1  
99                  3  

[100 rows x 15 columns]

### Boolean mask

In [26]:
mask = data['Ins_Age'] > 0.5
data[mask].head(10)

Id  Product_Info_1 Product_Info_2  Product_Info_3  Product_Info_4  \
0    2               1             D3              10        0.076923   
5   10               1             D2              26        0.230769   
7   14               1             D2              26        0.076923   
8   15               1             D3              26        0.230769   
9   16               1             E1              21        0.076923   
10  17               1             D3              26        0.128205   
12  19               1             A2              26        0.102564   
15  23               1             A7              26        0.000000   
21  31               1             A1              26        1.000000   
26  37               1             A1              26        1.000000   

    Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  ...  \
0                2               1               1  0.641791  0.581818  ...   
5                3               1               1  0.507463  0.836364  ...   
7                2               3               1  0.611940  0.781818  ...   
8                2               3               1  0.522388  0.618182  ...   
9                2               3               1  0.552239  0.600000  ...   
10               2               3               1  0.537313  0.690909  ...   
12               2               3               1  0.567164  0.618182  ...   
15               2               3               1  0.626866  0.672727  ...   
21               2               1               1  0.537313  0.709091  ...   
26               2               3               1  0.507463  0.654545  ...   

    Medical_Keyword_40  Medical_Keyword_41  Medical_Keyword_42  \
0                    0                   0                   0   
5                    0                   0                   0   
7                    0                   0                   0   
8                    0                   0                   0   
9                    0                   0                   0   
10                   0                   0                   0   
12                   0                   0                   0   
15                   0                   0                   0   
21                   0                   0                   0   
26                   0                   0                   0   

    Medical_Keyword_43  Medical_Keyword_44  Medical_Keyword_45  \
0                    0                   0                   0   
5                    0                   0                   0   
7                    0                   0                   0   
8                    0                   0                   0   
9                    0                   0                   0   
10                   0                   1                   0   
12                   0                   0                   0   
15                   0                   0                   0   
21                   0                   0                   0   
26                   0                   0                   0   

    Medical_Keyword_46  Medical_Keyword_47  Medical_Keyword_48  Response  
0                    0                   0                   0         8  
5                    0                   0                   0         8  
7                    0                   0                   0         1  
8                    0                   0                   0         8  
9                    0                   0                   0         1  
10                   0                   1                   1         6  
12                   0                   0                   0         7  
15                   0                   0                   0         5  
21                   0                   0                   0         5  
26                   0                   0                   0         6  

[10 rows x 128 columns]

### Get column by keyword(condition)

In [51]:
med_kw = data.columns.str.startswith('Medical_Keyword')
med_kw
data.loc[mask, med_kw]

Medical_Keyword_1  Medical_Keyword_2  Medical_Keyword_3  \
0                      0                  0                  0   
5                      0                  0                  0   
7                      0                  0                  0   
8                      0                  0                  0   
9                      0                  0                  0   
...                  ...                ...                ...   
59365                  0                  0                  0   
59366                  0                  0                  0   
59369                  1                  0                  1   
59371                  0                  0                  0   
59379                  0                  0                  0   

       Medical_Keyword_4  Medical_Keyword_5  Medical_Keyword_6  \
0                      0                  0                  0   
5                      0                  0                  0   
7                      0                  0                  0   
8                      0                  0                  0   
9                      0                  0                  0   
...                  ...                ...                ...   
59365                  0                  0                  0   
59366                  0                  0                  0   
59369                  0                  0                  0   
59371                  0                  0                  0   
59379                  0                  0                  0   

       Medical_Keyword_7  Medical_Keyword_8  Medical_Keyword_9  \
0                      0                  0                  0   
5                      0                  0                  0   
7                      0                  0                  0   
8                      0                  0                  0   
9                      0                  0                  0   
...                  ...                ...                ...   
59365                  0                  0                  0   
59366                  0                  0                  0   
59369                  0                  0                  0   
59371                  0                  0                  0   
59379                  0                  0                  0   

       Medical_Keyword_10  ...  Medical_Keyword_39  Medical_Keyword_40  \
0                       0  ...                   0                   0   
5                       0  ...                   0                   0   
7                       0  ...                   0                   0   
8                       0  ...                   0                   0   
9                       0  ...                   0                   0   
...                   ...  ...                 ...                 ...   
59365                   0  ...                   0                   0   
59366                   0  ...                   0                   0   
59369                   0  ...                   0                   0   
59371                   0  ...                   0                   0   
59379                   0  ...                   0                   1   

       Medical_Keyword_41  Medical_Keyword_42  Medical_Keyword_43  \
0                       0                   0                   0   
5                       0                   0                   0   
7                       0                   0                   0   
8                       0                   0                   0   
9                       0                   0                   0   
...                   ...                 ...                 ...   
59365                   0                   0                   0   
59366                   0                   0                   0   
59369                   0                   0                   0   
59371                   0                   0    

In [53]:
idx = data.loc[mask, med_kw].index
idx
data.loc[idx, 'Id']

0            2
5           10
7           14
8           15
9           16
         ...  
59365    79131
59366    79132
59369    79135
59371    79137
59379    79145
Name: Id, Length: 21087, dtype: int64

## Example 2

### Drop column, Ordinal encoding

In [58]:
data_ex2 = data.drop(columns='Id')
data_ex2

Product_Info_1 Product_Info_2  Product_Info_3  Product_Info_4  \
0                   1             D3              10        0.076923   
1                   1             A1              26        0.076923   
2                   1             E1              26        0.076923   
3                   1             D4              10        0.487179   
4                   1             D2              26        0.230769   
...               ...            ...             ...             ...   
59376               1             D1              10        0.230769   
59377               1             D3              26        0.230769   
59378               1             E1              26        0.076923   
59379               1             D2              10        0.230769   
59380               1             A8              26        0.076923   

       Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  \
0                   2               1               1  0.641791  0.581818   
1                   2               3               1  0.059701  0.600000   
2                   2               3               1  0.029851  0.745455   
3                   2               3               1  0.164179  0.672727   
4                   2               3               1  0.417910  0.654545   
...               ...             ...             ...       ...       ...   
59376               2               3               1  0.074627  0.709091   
59377               2               3               1  0.432836  0.800000   
59378               2               3               1  0.104478  0.745455   
59379               2               3               1  0.507463  0.690909   
59380               2               3               1  0.447761  0.781818   

             Wt  ...  Medical_Keyword_40  Medical_Keyword_41  \
0      0.148536  ...                   0                   0   
1      0.131799  ...                   0                   0   
2      0.288703  ...                   0                   0   
3      0.205021  ...                   0                   0   
4      0.234310  ...                   0                   0   
...         ...  ...                 ...                 ...   
59376  0.320084  ...                   0                   0   
59377  0.403766  ...                   0                   0   
59378  0.246862  ...                   0                   0   
59379  0.276151  ...                   1                   0   
59380  0.382845  ...                   0                   0   

       Medical_Keyword_42  Medical_Keyword_43  Medical_Keyword_44  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
59376                   0                   0                   0   
59377                   0                   0                   0   
59378                   0                   0                   0   
59379                   0                   0                   0   
59380                   0                   0                   0   

       Medical_Keyword_45  Medical_Keyword_46  Medical_Keyword_47  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
59376                   0                   0                   0   
59377                   0                   0                   0  

In [59]:
data_ex2.Product_Info_2 = pd.factorize(data_ex2.Product_Info_2)[0]
data_ex2

# # One-Hot encoding
# pd.get_dummies(data=data_ex2, columns=['Product_Info_2'])

Product_Info_1  Product_Info_2  Product_Info_3  Product_Info_4  \
0                   1               0              10        0.076923   
1                   1               1              26        0.076923   
2                   1               2              26        0.076923   
3                   1               3              10        0.487179   
4                   1               4              26        0.230769   
...               ...             ...             ...             ...   
59376               1               7              10        0.230769   
59377               1               0              26        0.230769   
59378               1               2              26        0.076923   
59379               1               4              10        0.230769   
59380               1               5              26        0.076923   

       Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  \
0                   2               1               1  0.641791  0.581818   
1                   2               3               1  0.059701  0.600000   
2                   2               3               1  0.029851  0.745455   
3                   2               3               1  0.164179  0.672727   
4                   2               3               1  0.417910  0.654545   
...               ...             ...             ...       ...       ...   
59376               2               3               1  0.074627  0.709091   
59377               2               3               1  0.432836  0.800000   
59378               2               3               1  0.104478  0.745455   
59379               2               3               1  0.507463  0.690909   
59380               2               3               1  0.447761  0.781818   

             Wt  ...  Medical_Keyword_40  Medical_Keyword_41  \
0      0.148536  ...                   0                   0   
1      0.131799  ...                   0                   0   
2      0.288703  ...                   0                   0   
3      0.205021  ...                   0                   0   
4      0.234310  ...                   0                   0   
...         ...  ...                 ...                 ...   
59376  0.320084  ...                   0                   0   
59377  0.403766  ...                   0                   0   
59378  0.246862  ...                   0                   0   
59379  0.276151  ...                   1                   0   
59380  0.382845  ...                   0                   0   

       Medical_Keyword_42  Medical_Keyword_43  Medical_Keyword_44  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
59376                   0                   0                   0   
59377                   0                   0                   0   
59378                   0                   0                   0   
59379                   0                   0                   0   
59380                   0                   0                   0   

       Medical_Keyword_45  Medical_Keyword_46  Medical_Keyword_47  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
59376                   0                   0                   0   
59377                   0                   0          

## Proximity

### L2 distance(Euclidean distance)

In [86]:
def euclidean(a, b):
    return np.sqrt(
        np.sum(
            np.square(a - b) # Element-wise
        )
    )

In [87]:
f = lambda x, y: np.sqrt(np.sum(np.square(x, y)))
f(v1, v2)

3.7416573867739413

### Cosine similarity

In [88]:
def cosine_sim(a, b):
    # Numerator: a o b
    dot = a @ b
    
    # Denominator: ||a||, ||b||
    norm = np.linalg.norm(a) * np.linalg.norm(b) + 1e-12 # Prevent Divided by 0
    
    sim = dot / norm
    if np.isnan(sim):
        return 0
    else:
        return sim

In [89]:
print(euclidean(v1, v2))
cosine_sim(v1, v2)

6.324555320336759


0.9719086448808438

In [93]:
dist = np.sqrt(np.sum(np.square(v1 - v2)))
dist2 = np.linalg.norm(v1 - v2)
print(dist, dist == dist2)

6.324555320336759 True


## Example 3

### Get closest customer to customer_6

In [120]:
data_light = data.iloc[:, :15].drop(columns='Id')
data_light.Product_Info_2 = pd.factorize(data_light.Product_Info_2)[0]
data_light

Product_Info_1  Product_Info_2  Product_Info_3  Product_Info_4  \
0                   1               0              10        0.076923   
1                   1               1              26        0.076923   
2                   1               2              26        0.076923   
3                   1               3              10        0.487179   
4                   1               4              26        0.230769   
...               ...             ...             ...             ...   
59376               1               7              10        0.230769   
59377               1               0              26        0.230769   
59378               1               2              26        0.076923   
59379               1               4              10        0.230769   
59380               1               5              26        0.076923   

       Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  \
0                   2               1               1  0.641791  0.581818   
1                   2               3               1  0.059701  0.600000   
2                   2               3               1  0.029851  0.745455   
3                   2               3               1  0.164179  0.672727   
4                   2               3               1  0.417910  0.654545   
...               ...             ...             ...       ...       ...   
59376               2               3               1  0.074627  0.709091   
59377               2               3               1  0.432836  0.800000   
59378               2               3               1  0.104478  0.745455   
59379               2               3               1  0.507463  0.690909   
59380               2               3               1  0.447761  0.781818   

             Wt       BMI  Employment_Info_1  Employment_Info_2  \
0      0.148536  0.323008              0.028                 12   
1      0.131799  0.272288              0.000                  1   
2      0.288703  0.428780              0.030                  9   
3      0.205021  0.352438              0.042                  9   
4      0.234310  0.424046              0.027                  9   
...         ...       ...                ...                ...   
59376  0.320084  0.519103              0.020                  1   
59377  0.403766  0.551119              0.100                  9   
59378  0.246862  0.360969              0.035                  9   
59379  0.276151  0.462452              0.038                  9   
59380  0.382845  0.539563              0.123                  9   

       Employment_Info_3  
0                      1  
1                      3  
2                      1  
3                      1  
4                      1  
...                  ...  
59376                  3  
59377                  1  
59378                  1  
59379                  1  
59380                  1  

[59381 rows x 14 columns]

### Euclidean dist.

In [121]:
target = data_light.loc[2]
distances = []

for idx, row in data_light.iterrows():
    distances.append(euclidean(target, row))

distances

[16.535782004204712,
 8.31096004346075,
 0.0,
 16.037600149954404,
 2.0458527522719434,
 6.734334643641273,
 18.253080654233024,
 3.6581266677540745,
 2.077498695235857,
 9.660195375560171,
 2.067024258786202,
 6.091255246711154,
 4.041658792791359,
 5.120912100506553,
 6.110204819641582,
 6.032799078243638,
 5.216477531508588,
 2.0414088274149034,
 2.032873719529673,
 1.12739899471373,
 2.0655106745330185,
 6.494700910403046,
 1.1034313431419105,
 4.003721831344186,
 5.4069451433255455,
 7.622404127385059,
 3.334169444386282,
 2.0144368366997423,
 1.1919644099407252,
 2.275675092182342,
 2.871422746212288,
 7.082799293970738,
 1.029698313320298,
 4.28333289816827,
 5.051954797785934,
 18.122133870707376,
 11.492088096991216,
 2.052553165197456,
 8.807803651578261,
 8.509568938463344,
 5.522993855614589,
 9.662246659771055,
 16.29204320201429,
 2.905872747723984,
 8.513607696930583,
 6.753440131495716,
 5.8689178931769055,
 2.0631605188975413,
 1.078851691821121,
 16.287032420926497,
 

In [122]:
distances[2] = 99999
distances

[16.535782004204712,
 8.31096004346075,
 99999,
 16.037600149954404,
 2.0458527522719434,
 6.734334643641273,
 18.253080654233024,
 3.6581266677540745,
 2.077498695235857,
 9.660195375560171,
 2.067024258786202,
 6.091255246711154,
 4.041658792791359,
 5.120912100506553,
 6.110204819641582,
 6.032799078243638,
 5.216477531508588,
 2.0414088274149034,
 2.032873719529673,
 1.12739899471373,
 2.0655106745330185,
 6.494700910403046,
 1.1034313431419105,
 4.003721831344186,
 5.4069451433255455,
 7.622404127385059,
 3.334169444386282,
 2.0144368366997423,
 1.1919644099407252,
 2.275675092182342,
 2.871422746212288,
 7.082799293970738,
 1.029698313320298,
 4.28333289816827,
 5.051954797785934,
 18.122133870707376,
 11.492088096991216,
 2.052553165197456,
 8.807803651578261,
 8.509568938463344,
 5.522993855614589,
 9.662246659771055,
 16.29204320201429,
 2.905872747723984,
 8.513607696930583,
 6.753440131495716,
 5.8689178931769055,
 2.0631605188975413,
 1.078851691821121,
 16.287032420926497,

In [123]:
np.argmin(distances)

18154

In [124]:
v3 = np.array([1, 1, 1])
v4 = np.array([2, 2, 2])
v3, v4

(array([1, 1, 1]), array([2, 2, 2]))

In [125]:
euclidean(v3, v4)

1.7320508075688772

In [126]:
cosine_sim(v3, v4)

0.9999999999998335